<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7_w5csg' shared service.

return $this->privates['.service_locator.7_w5csg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::showByEpisode' => ['privates', '.service_locator.TlC5_Zq', 'get_ServiceLocator_TlC5ZqService.php', true],
    'App\\Controller\\WildController::showByProgram' => ['privates', '.service_locator.0WrsdWq', 'get_ServiceLocator_0WrsdWqService.php', true],
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\WildController:showByEpisode' => ['privates', '.service_locator.TlC5_Zq', 'get_ServiceLocator_TlC5ZqService.php', true],
    'App\\Controller\\WildController:showByProgram' => ['privates', '.service_locator.0WrsdWq', 'get_ServiceLocator_0WrsdWqService.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
], [
    'App\\Controller\\WildController::showByEpisode' => '?',
    'App\\Controller\\WildController::showByProgram' => '?',
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\WildController:showByEpisode' => '?',
    'App\\Controller\\WildController:showByProgram' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
]);
