<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG6017B2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG6017B2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG6017B2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG6017B2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG6017B2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G6017B2',
    'container.build_id' => '52907bf5',
    'container.build_time' => 1575991779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG6017B2');
