<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.msQ6HY7' shared service.

return $this->privates['.service_locator.msQ6HY7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::addCategory' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\WildController::showByEpisode' => ['privates', '.service_locator.PqXbmwR', 'get_ServiceLocator_PqXbmwRService.php', true],
    'App\\Controller\\WildController::showByProgram' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\WildController:addCategory' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\WildController:showByEpisode' => ['privates', '.service_locator.PqXbmwR', 'get_ServiceLocator_PqXbmwRService.php', true],
    'App\\Controller\\WildController:showByProgram' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
], [
    'App\\Controller\\WildController::addCategory' => '?',
    'App\\Controller\\WildController::showByEpisode' => '?',
    'App\\Controller\\WildController::showByProgram' => '?',
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\WildController:addCategory' => '?',
    'App\\Controller\\WildController:showByEpisode' => '?',
    'App\\Controller\\WildController:showByProgram' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
]);
