<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXK9zDVc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXK9zDVc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXK9zDVc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXK9zDVc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXK9zDVc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XK9zDVc',
    'container.build_id' => '55bcaae9',
    'container.build_time' => 1574782785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXK9zDVc');
