<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUa98xnW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUa98xnW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUa98xnW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUa98xnW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUa98xnW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ua98xnW',
    'container.build_id' => '70870b56',
    'container.build_time' => 1574692361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUa98xnW');
